name: Cron

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    environment:
      name: Painted Mountain
    steps:
    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: rust.yml
        workflow_conclusion: success
        branch: master
    - name: Make Executable
      id: make-executable
      run: chmod +x Binary/lds-secretary
    - name: Write creds.json file
      id: write-creds
      env:
        CREDS_DATA: ${{ secrets.CREDS_DATA }}
      run: echo $CREDS_DATA > creds.json
    - name: Run Sync
      id: run-sync
      env:
        LDS_USERNAME: ${{ secrets.LDS_USERNAME }}
        LDS_PASSWORD: ${{ secrets.LDS_PASSWORD }}
        GOOGLE_APPLICATION_CREDENTIALS: creds.json
        DOCUMENT_ID: ${{ vars.DOCUMENT_ID }}
        SHEET_NAME: ${{ vars.SHEET_NAME }}
      run: Binary/lds-secretary
